-- Connect to the soundwave database before running this schema.
-- Create it separately if needed: CREATE DATABASE soundwave;

CREATE TABLE roles
(
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(30)             NOT NULL,
    name        VARCHAR(80)            NOT NULL,
    description VARCHAR(500)           NULL,
    created_at  TIMESTAMP(3) WITHOUT TIME ZONE            NOT NULL
        CONSTRAINT DF_roles_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_roles PRIMARY KEY (id),
    CONSTRAINT UQ_roles_code UNIQUE (code)
);
CREATE TABLE app_users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id           SMALLINT              NOT NULL,
    email             VARCHAR(320)         NOT NULL,
    password_hash     VARCHAR(255)          NOT NULL,
    status            VARCHAR(30)           NOT NULL
        CONSTRAINT DF_app_users_status DEFAULT 'PENDING',
    email_verified_at TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    last_login_at     TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    deleted_at        TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    created_at        TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL
        CONSTRAINT DF_app_users_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at        TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL
        CONSTRAINT DF_app_users_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_app_users PRIMARY KEY (id),
    CONSTRAINT UQ_app_users_email UNIQUE (email),
    CONSTRAINT FK_app_users_roles
        FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT CK_app_users_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'BANNED'))
);
CREATE INDEX IX_app_users_role_id
    ON app_users(role_id);
CREATE INDEX IX_app_users_status
    ON app_users(status)
    WHERE deleted_at IS NULL;
CREATE TABLE user_profiles
(
    user_id          BIGINT         NOT NULL,
    username         VARCHAR(50)   NOT NULL,
    display_name     VARCHAR(120)  NOT NULL,
    bio              VARCHAR(1000) NULL,
    avatar_public_id VARCHAR(255)  NULL,
    avatar_url       VARCHAR(2048) NULL,
    date_of_birth    DATE           NULL,
    country_code     CHAR(2)        NULL,
    created_at       TIMESTAMP(3) WITHOUT TIME ZONE   NOT NULL
        CONSTRAINT DF_user_profiles_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at       TIMESTAMP(3) WITHOUT TIME ZONE   NOT NULL
        CONSTRAINT DF_user_profiles_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_user_profiles PRIMARY KEY (user_id),
    CONSTRAINT UQ_user_profiles_username UNIQUE (username),
    CONSTRAINT FK_user_profiles_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id)
);
CREATE TABLE email_verification_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                NOT NULL,
    token_hash VARCHAR(255)          NOT NULL,
    expires_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL,
    used_at    TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL
        CONSTRAINT DF_email_verification_tokens_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_email_verification_tokens PRIMARY KEY (id),
    CONSTRAINT UQ_email_verification_tokens_hash UNIQUE (token_hash),
    CONSTRAINT FK_email_verification_tokens_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT CK_email_verification_tokens_expiry
        CHECK (expires_at > created_at)
);
CREATE INDEX IX_email_verification_tokens_user_id
    ON email_verification_tokens(user_id, expires_at);
CREATE TABLE password_reset_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                NOT NULL,
    token_hash VARCHAR(255)          NOT NULL,
    expires_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL,
    used_at    TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL
        CONSTRAINT DF_password_reset_tokens_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT UQ_password_reset_tokens_hash UNIQUE (token_hash),
    CONSTRAINT FK_password_reset_tokens_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT CK_password_reset_tokens_expiry
        CHECK (expires_at > created_at)
);
CREATE INDEX IX_password_reset_tokens_user_id
    ON password_reset_tokens(user_id, expires_at);
CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                NOT NULL,
    token_hash VARCHAR(255)          NOT NULL,
    expires_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL,
    revoked_at TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL
        CONSTRAINT DF_refresh_tokens_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT UQ_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT FK_refresh_tokens_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT CK_refresh_tokens_expiry
        CHECK (expires_at > created_at)
);
CREATE INDEX IX_refresh_tokens_active_by_user
    ON refresh_tokens(user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE TABLE genres
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(100)        NOT NULL,
    slug               VARCHAR(100)         NOT NULL,
    description        VARCHAR(1000)       NULL,
    is_active          BOOLEAN                  NOT NULL
        CONSTRAINT DF_genres_is_active DEFAULT TRUE,
    created_by_user_id BIGINT               NULL,
    created_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_genres_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_genres_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_genres PRIMARY KEY (id),
    CONSTRAINT UQ_genres_name UNIQUE (name),
    CONSTRAINT UQ_genres_slug UNIQUE (slug),
    CONSTRAINT FK_genres_created_by_app_users
        FOREIGN KEY (created_by_user_id) REFERENCES app_users(id)
);
CREATE TABLE albums
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by_user_id BIGINT               NOT NULL,
    title              VARCHAR(200)        NOT NULL,
    slug               VARCHAR(220)         NOT NULL,
    description        VARCHAR(2000)       NULL,
    status             VARCHAR(30)          NOT NULL
        CONSTRAINT DF_albums_status DEFAULT 'DRAFT',
    cover_public_id    VARCHAR(255)        NULL,
    cover_url          VARCHAR(2048)       NULL,
    release_date       DATE                 NULL,
    published_at       TIMESTAMP(3) WITHOUT TIME ZONE         NULL,
    created_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_albums_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_albums_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_albums PRIMARY KEY (id),
    CONSTRAINT UQ_albums_slug UNIQUE (slug),
    CONSTRAINT FK_albums_created_by_app_users
        FOREIGN KEY (created_by_user_id) REFERENCES app_users(id),
    CONSTRAINT CK_albums_status
        CHECK (status IN ('DRAFT', 'PUBLISHED'))
);
CREATE INDEX IX_albums_created_by_user_id
    ON albums(created_by_user_id, status);
CREATE TABLE tracks
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uploader_user_id        BIGINT               NOT NULL,
    album_id                BIGINT               NULL,
    genre_id                BIGINT               NOT NULL,
    title                   VARCHAR(200)        NOT NULL,
    slug                    VARCHAR(220)         NOT NULL,
    description             VARCHAR(2000)       NULL,
    track_number            SMALLINT             NULL,
    publication_status      VARCHAR(30)          NOT NULL
        CONSTRAINT DF_tracks_publication_status DEFAULT 'DRAFT',
    approved_at             TIMESTAMP(3) WITHOUT TIME ZONE         NULL,
    latest_rejection_reason VARCHAR(1000)       NULL,
    audio_public_id         VARCHAR(255)        NOT NULL,
    audio_url               VARCHAR(2048)       NOT NULL,
    audio_format            VARCHAR(20)          NOT NULL,
    duration_ms             INT                  NOT NULL,
    cover_public_id         VARCHAR(255)        NULL,
    cover_url               VARCHAR(2048)       NULL,
    play_count_cache        BIGINT               NOT NULL
        CONSTRAINT DF_tracks_play_count_cache DEFAULT 0,
    created_at              TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_tracks_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at              TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_tracks_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_tracks PRIMARY KEY (id),
    CONSTRAINT UQ_tracks_slug UNIQUE (slug),
    CONSTRAINT FK_tracks_uploader_app_users
        FOREIGN KEY (uploader_user_id) REFERENCES app_users(id),
    CONSTRAINT FK_tracks_albums
        FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE SET NULL,
    CONSTRAINT FK_tracks_genres
        FOREIGN KEY (genre_id) REFERENCES genres(id),
    CONSTRAINT CK_tracks_publication_status
        CHECK (publication_status IN
            ('DRAFT', 'PENDING', 'PUBLISHED', 'REJECTED', 'TAKEN_DOWN')),
    CONSTRAINT CK_tracks_track_number
        CHECK (track_number IS NULL OR track_number > 0),
    CONSTRAINT CK_tracks_duration_ms
        CHECK (duration_ms >= 0),
    CONSTRAINT CK_tracks_play_count_cache
        CHECK (play_count_cache >= 0)
);
CREATE INDEX IX_tracks_public_catalog
    ON tracks(publication_status, genre_id, created_at DESC)
    INCLUDE (title, slug, uploader_user_id, album_id, cover_url, duration_ms, play_count_cache);
CREATE INDEX IX_tracks_uploader_user_id
    ON tracks(uploader_user_id, publication_status, created_at DESC);
CREATE INDEX IX_tracks_album_id
    ON tracks(album_id, track_number);
CREATE TABLE track_submissions
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    track_id             BIGINT               NOT NULL,
    submitted_by_user_id BIGINT               NOT NULL,
    reviewer_user_id     BIGINT               NULL,
    status               VARCHAR(30)          NOT NULL
        CONSTRAINT DF_track_submissions_status DEFAULT 'PENDING',
    submitter_note       VARCHAR(2000)       NULL,
    reviewer_note        VARCHAR(2000)       NULL,
    rejection_reason     VARCHAR(1000)       NULL,
    submitted_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_track_submissions_submitted_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    reviewed_at          TIMESTAMP(3) WITHOUT TIME ZONE         NULL,

    CONSTRAINT PK_track_submissions PRIMARY KEY (id),
    CONSTRAINT FK_track_submissions_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id),
    CONSTRAINT FK_track_submissions_submitter_app_users
        FOREIGN KEY (submitted_by_user_id) REFERENCES app_users(id),
    CONSTRAINT FK_track_submissions_reviewer_app_users
        FOREIGN KEY (reviewer_user_id) REFERENCES app_users(id),
    CONSTRAINT CK_track_submissions_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CK_track_submissions_review_result
        CHECK (
            (status = 'PENDING' AND reviewed_at IS NULL)
            OR
            (status IN ('APPROVED', 'REJECTED')
                AND reviewer_user_id IS NOT NULL
                AND reviewed_at IS NOT NULL)
        ),
    CONSTRAINT CK_track_submissions_rejection_reason
        CHECK (status <> 'REJECTED' OR rejection_reason IS NOT NULL)
);
CREATE UNIQUE INDEX UX_track_submissions_one_pending_per_track
    ON track_submissions(track_id)
    WHERE status = 'PENDING';
CREATE INDEX IX_track_submissions_moderation_queue
    ON track_submissions(status, submitted_at)
    INCLUDE (track_id, submitted_by_user_id, reviewer_user_id);
CREATE TABLE lyric_languages
(
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(10)            NOT NULL,
    name        VARCHAR(50)           NOT NULL,
    created_at  TIMESTAMP(3) WITHOUT TIME ZONE           NOT NULL
        CONSTRAINT DF_lyric_languages_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_lyric_languages PRIMARY KEY (id),
    CONSTRAINT UQ_lyric_languages_code UNIQUE (code)
);
CREATE TABLE official_lyrics
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    track_id           BIGINT               NOT NULL,
    language_id        SMALLINT             NOT NULL,
    lyric_content      TEXT        NOT NULL,
    status             VARCHAR(30)          NOT NULL
        CONSTRAINT DF_official_lyrics_status DEFAULT 'DRAFT',
    created_by_user_id BIGINT               NOT NULL,
    created_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_official_lyrics_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at         TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_official_lyrics_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_official_lyrics PRIMARY KEY (id),
    CONSTRAINT UQ_official_lyrics_track_language
        UNIQUE (track_id, language_id),
    CONSTRAINT FK_official_lyrics_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE,
    CONSTRAINT FK_official_lyrics_languages
        FOREIGN KEY (language_id) REFERENCES lyric_languages(id),
    CONSTRAINT FK_official_lyrics_created_by_app_users
        FOREIGN KEY (created_by_user_id) REFERENCES app_users(id),
    CONSTRAINT CK_official_lyrics_status
        CHECK (status IN ('DRAFT', 'PUBLISHED'))
);
CREATE INDEX IX_official_lyrics_public
    ON official_lyrics(track_id, status, language_id);
CREATE TABLE personal_lyrics
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT               NOT NULL,
    track_id      BIGINT               NOT NULL,
    language_id   SMALLINT             NOT NULL,
    lyric_type    VARCHAR(20)          NOT NULL
        CONSTRAINT DF_personal_lyrics_type DEFAULT 'CUSTOM',
    lyric_content TEXT        NOT NULL,
    created_at    TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_personal_lyrics_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at    TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_personal_lyrics_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_personal_lyrics PRIMARY KEY (id),
    CONSTRAINT UQ_personal_lyrics_user_track_lang_type
        UNIQUE (user_id, track_id, language_id, lyric_type),
    CONSTRAINT FK_personal_lyrics_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT FK_personal_lyrics_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE,
    CONSTRAINT FK_personal_lyrics_languages
        FOREIGN KEY (language_id) REFERENCES lyric_languages(id),
    CONSTRAINT CK_personal_lyrics_type
        CHECK (lyric_type IN ('CUSTOM', 'TRANSLATION'))
);
CREATE INDEX IX_personal_lyrics_user_track
    ON personal_lyrics(user_id, track_id);
CREATE TABLE listening_history
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              BIGINT               NOT NULL,
    track_id             BIGINT               NOT NULL,
    listened_duration_ms INT                  NOT NULL,
    completed            BOOLEAN                  NOT NULL
        CONSTRAINT DF_listening_history_completed DEFAULT FALSE,
    played_at            TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_listening_history_played_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_listening_history PRIMARY KEY (id),
    CONSTRAINT FK_listening_history_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT FK_listening_history_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id),
    CONSTRAINT CK_listening_history_duration
        CHECK (listened_duration_ms >= 0)
);
CREATE INDEX IX_listening_history_user_played_at
    ON listening_history(user_id, played_at DESC)
    INCLUDE (track_id, listened_duration_ms, completed);
CREATE TABLE favorites
(
    user_id    BIGINT       NOT NULL,
    track_id   BIGINT       NOT NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
        CONSTRAINT DF_favorites_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_favorites PRIMARY KEY (user_id, track_id),
    CONSTRAINT FK_favorites_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT FK_favorites_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id)
);
CREATE INDEX IX_favorites_track_id
    ON favorites(track_id);
CREATE TABLE playlists
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_user_id   BIGINT               NOT NULL,
    name            VARCHAR(150)        NOT NULL,
    description     VARCHAR(1000)       NULL,
    visibility      VARCHAR(20)          NOT NULL
        CONSTRAINT DF_playlists_visibility DEFAULT 'PRIVATE',
    cover_public_id VARCHAR(255)        NULL,
    cover_url       VARCHAR(2048)       NULL,
    created_at      TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_playlists_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at      TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_playlists_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_playlists PRIMARY KEY (id),
    CONSTRAINT FK_playlists_owner_app_users
        FOREIGN KEY (owner_user_id) REFERENCES app_users(id),
    CONSTRAINT CK_playlists_visibility
        CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);
CREATE INDEX IX_playlists_owner_user_id
    ON playlists(owner_user_id, updated_at DESC);
CREATE INDEX IX_playlists_public
    ON playlists(visibility, updated_at DESC)
    WHERE visibility = 'PUBLIC';
CREATE TABLE playlist_tracks
(
    playlist_id     BIGINT       NOT NULL,
    track_id        BIGINT       NOT NULL,
    added_by_user_id BIGINT      NOT NULL,
    position        INT          NOT NULL,
    added_at        TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
        CONSTRAINT DF_playlist_tracks_added_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_playlist_tracks PRIMARY KEY (playlist_id, track_id),
    CONSTRAINT UQ_playlist_tracks_position UNIQUE (playlist_id, position),
    CONSTRAINT FK_playlist_tracks_playlists
        FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
    CONSTRAINT FK_playlist_tracks_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE,
    CONSTRAINT FK_playlist_tracks_added_by_app_users
        FOREIGN KEY (added_by_user_id) REFERENCES app_users(id),
    CONSTRAINT CK_playlist_tracks_position CHECK (position > 0)
);
CREATE INDEX IX_playlist_tracks_track_id
    ON playlist_tracks(track_id);
CREATE TABLE content_reports
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    track_id             BIGINT               NOT NULL,
    submitted_by_user_id BIGINT               NOT NULL,
    handled_by_user_id   BIGINT               NULL,
    category             VARCHAR(50)          NOT NULL,
    description          VARCHAR(2000)       NOT NULL,
    status               VARCHAR(30)          NOT NULL
        CONSTRAINT DF_content_reports_status DEFAULT 'PENDING',
    resolution_note      VARCHAR(2000)       NULL,
    created_at           TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_content_reports_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    handled_at           TIMESTAMP(3) WITHOUT TIME ZONE         NULL,
    updated_at           TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_content_reports_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_content_reports PRIMARY KEY (id),
    CONSTRAINT FK_content_reports_tracks
        FOREIGN KEY (track_id) REFERENCES tracks(id),
    CONSTRAINT FK_content_reports_submitter_app_users
        FOREIGN KEY (submitted_by_user_id) REFERENCES app_users(id),
    CONSTRAINT FK_content_reports_handler_app_users
        FOREIGN KEY (handled_by_user_id) REFERENCES app_users(id),
    CONSTRAINT CK_content_reports_category
        CHECK (category IN
            ('COPYRIGHT', 'INAPPROPRIATE_CONTENT', 'INCORRECT_METADATA', 'OTHER')),
    CONSTRAINT CK_content_reports_status
        CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT CK_content_reports_handling
        CHECK (
            (status IN ('PENDING', 'WITHDRAWN') AND handled_at IS NULL)
            OR
            (status IN ('RESOLVED', 'REJECTED')
                AND handled_by_user_id IS NOT NULL
                AND handled_at IS NOT NULL
                AND resolution_note IS NOT NULL)
        )
);
CREATE INDEX IX_content_reports_submitter
    ON content_reports(submitted_by_user_id, created_at DESC);
CREATE INDEX IX_content_reports_moderation_queue
    ON content_reports(status, created_at)
    INCLUDE (track_id, submitted_by_user_id, category);
CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                NOT NULL,
    type       VARCHAR(50)           NOT NULL,
    title      VARCHAR(200)         NOT NULL,
    message    VARCHAR(2000)        NOT NULL,
    action_url VARCHAR(2048)        NULL,
    read_at    TIMESTAMP(3) WITHOUT TIME ZONE          NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE          NOT NULL
        CONSTRAINT DF_notifications_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_notifications PRIMARY KEY (id),
    CONSTRAINT FK_notifications_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT CK_notifications_type
        CHECK (type IN
            ('TRACK_APPROVED', 'TRACK_REJECTED', 'TRACK_TAKEN_DOWN',
             'REPORT_RESOLVED', 'REPORT_REJECTED',
             'ACCOUNT_STATUS_CHANGED', 'ROLE_CHANGED', 'SYSTEM'))
);
CREATE INDEX IX_notifications_user_unread
    ON notifications(user_id, read_at, created_at DESC);
CREATE TABLE system_reviews
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT               NOT NULL,
    rating      SMALLINT              NOT NULL,
    comment     VARCHAR(2000)       NULL,
    status      VARCHAR(30)          NOT NULL
        CONSTRAINT DF_system_reviews_status DEFAULT 'PENDING',
    created_at  TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_system_reviews_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
    updated_at  TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
        CONSTRAINT DF_system_reviews_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

    CONSTRAINT PK_system_reviews PRIMARY KEY (id),
    CONSTRAINT FK_system_reviews_app_users
        FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT CK_system_reviews_rating
        CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT CK_system_reviews_status
        CHECK (status IN ('PENDING', 'ACKNOWLEDGED', 'HIDDEN'))
);
CREATE INDEX IX_system_reviews_user_id
    ON system_reviews(user_id, created_at DESC);
CREATE INDEX IX_system_reviews_status
    ON system_reviews(status, created_at DESC);
INSERT INTO roles (code, name, description) VALUES ('LISTENER', 'Listener', 'Standard user for streaming and managing personal library.') ON CONFLICT (code) DO NOTHING;

INSERT INTO roles (code, name, description) VALUES ('STAFF', 'Staff', 'Content moderation staff managing tracks, reports, and official lyrics.') ON CONFLICT (code) DO NOTHING;

INSERT INTO roles (code, name, description) VALUES ('ADMIN', 'Administrator', 'System administrator managing users, roles, genres, and platform analytics.') ON CONFLICT (code) DO NOTHING;
INSERT INTO lyric_languages (code, name) VALUES ('vi', 'Vietnamese') ON CONFLICT (code) DO NOTHING;

INSERT INTO lyric_languages (code, name) VALUES ('en', 'English') ON CONFLICT (code) DO NOTHING;

INSERT INTO lyric_languages (code, name) VALUES ('ja', 'Japanese') ON CONFLICT (code) DO NOTHING;
SELECT table_schema AS schema_name, table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
