CREATE TABLE IF NOT EXISTS system_reviews
    (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id     BIGINT               NOT NULL,
        rating      SMALLINT              NOT NULL,
        comment     VARCHAR(2000)       NULL,
        status      VARCHAR(30)          NOT NULL
            CONSTRAINT DF_system_reviews_status DEFAULT 'PENDING',
        created_at  TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
            CONSTRAINT DF_system_reviews_created_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),
        updated_at  TIMESTAMP(3) WITHOUT TIME ZONE         NOT NULL
            CONSTRAINT DF_system_reviews_updated_at DEFAULT timezone('UTC', CURRENT_TIMESTAMP(3)),

        CONSTRAINT PK_system_reviews PRIMARY KEY (id),
        CONSTRAINT FK_system_reviews_app_users
            FOREIGN KEY (user_id) REFERENCES app_users(id),
        CONSTRAINT CK_system_reviews_rating
            CHECK (rating >= 1 AND rating <= 5),
        CONSTRAINT CK_system_reviews_status
            CHECK (status IN ('PENDING', 'ACKNOWLEDGED', 'HIDDEN'))
);
CREATE INDEX IF NOT EXISTS IX_system_reviews_user_id
        ON system_reviews(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS IX_system_reviews_status
        ON system_reviews(status, created_at DESC);
